name: Build Flutter Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Check Flutter version
        run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Run linter
        run: flutter analyze
      
      - name: Create keystore file
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app/keystores
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/keystores/antivirus-keystore.jks
      
      - name: Create key.properties
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "storePassword=$STORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=app/keystores/antivirus-keystore.jks" >> android/key.properties
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Build Split APKs (Per ABI)
        run: flutter build apk --split-per-abi --release
      
      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      
      - name: Upload Split APKs
        uses: actions/upload-artifact@v3
        with:
          name: split-apks
          path: build/app/outputs/flutter-apk/*-release.apk
      
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab